### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by cruzecontrol** [therealklanni/slack-invite-request#7]
Full error text below.  New install after this was running fine for years on a FreeBSD box.  That box died, so new install on Bodhi Linux.  Installs fine, the web site is exposed, people can submit requests, but they never show up in slack.  Digging into the logs I find the following error log:
TypeError: Cannot read property 'call' of undefined
    at GotError.get (/home/joe/hubot/node_modules/nested-error-stacks/index.js:22:52)
    at process.uncaughtListener (/home/joe/.nvm/versions/node/v10.11.0/lib/node_modules/pm2/node_modules/@pm2/io/build/main/src/features/notify.js:81:40)
    at Object.onceWrapper (events.js:273:13)
    at process.emit (events.js:187:15)
    at process.EventEmitter.emit (domain.js:442:20)
    at process._fatalException (internal/bootstrap/node.js:485:27)
/home/joe/hubot/node_modules/nested-error-stacks/index.js:22
                var stack = oldStackDescriptor.get.call(this);

FYI, the server is started via 'pm2,' the same process manager I ran it under in FreeBSD.

**Comment by therealklanni** [comment]
This hasn't been tested in Node v10.11.0. Please try an earlier version. 

Also, `pm2` is not officially supported. If the problem is `pm2`, that's outside the scope of SIR.

**Comment by cruzecontrol** [comment]
The issue was with pm2.  It works fine under nodemon.  Sorry for the false alarm.
